############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Policy"
url = "policies/"
weight = 3

[[main]]
name = "Support"
url = "support/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Policy"
url = "policies/"
weight = 2

[[footer]]
name = "Support"
url = "support/"
weight = 3

[[footer]]
name = "Blog"
url = "blog/"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 5
