#################### default parameters ################################
# favicon
favicon = "images/symbol_tdc_color.png"
# logo
logo = "images/logo_tdc_horizontal_color.svg"
logo_darkmode = "images/logo_tdc_horizontal_white.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "304px"
logo_height = "55px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "The DeFi Collective"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]

# Author info (eg for RSS)
[author]
email = "hello@deficollective.org"
name = "Webmaster"

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "DeFiScan"
link = "https://www.defiscan.info/"

# search
# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#4800b9"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true


# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["DeFi", "Decentralized Finance", "Unstoppable DeFi", "Non-profit"]
description = "The DeFi Collective"
author = "DeFi Collective"
image = "images/logo_tdc_horizontal_color.svg"

# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]
